version: "3.3"

services:
 mysql:
  image: mariadb:latest
  restart: always
  ports:
   - "3306:3306"
  environment:
   MYSQL_ROOT_PASSWORD: MyDBRoot123
   MYSQL_DATABASE: php
   MYSQL_USER: php
   MYSQL_PASSWORD: php
  networks:
   - app-network

 mynginx:
  image: nginx:latest
  ports:
   - "8080:80"
  volumes:
   - $HOME/cca2/src:/var/www/html
   - $HOME/cca2/src/nginx.ini:/etc/nginx/conf.d/default.conf
   - $HOME/cca2/src/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
   - $HOME/cca2/src/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
  links:
   - myphp
  privileged: true
  networks:
   - app-network

 myphp:
  build: ./src/php
  restart: always
  ports:
   - "9000:9000"
  links:
   - mysql
  volumes:
   - $HOME/cca2/src:/var/www/html
  privileged: true
  networks:
   - app-network

 myredis:
  image: redis:latest
  restart: always
  ports:
   - "6379:6379"
  networks:
   - app-network
volumes:
  database: {}
networks:
  app-network:
   driver: bridge
